### ISSUE TITLE
Build failure after commit 1688928

### ISSUE THREAD

**Issue by maronows** [kyberpunk/openthread#17]
After latest update build is now failing on my system with following errors (plenty of them):

/usr/local/Cellar/arm-none-eabi-gcc/9-2019-q4-major/gcc/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: ../../../src/core/libopenthread-ftd.a(libopenthread_ftd_a-mqttsn_serializer.o): in function `ot::Mqttsn::DisconnectMessage::~DisconnectMessage()':
/Users/marcin/devel/mqttsn/openthread/examples/../src/core/mqttsn/mqttsn_serializer.hpp:841: undefined reference to `operator delete(void*)'

What compiler are you using in your setup?

**Comment by kyberpunk** [comment]
Thank you for notification. I've removed the virtual constructor. I've build the project with custom build in IDE with gnu++11 and standard library which is not supported by OpenThread build.

I like object oriented paradigm but using polymorphism in embedded project is definitelly not a good idea. Virtual destructor is basically not needed in current implementation since it is not overridden. But it is not safe without it. I have to consider refactoring the code without virtual functions.
